"""make language nullable

Revision ID: 5ac118d77388
Revises: e348166cb21d
Create Date: 2026-07-04 21:33:11.767032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5ac118d77388'
down_revision: Union[str, Sequence[str], None] = 'e348166cb21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.alter_column('books', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'page_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'page_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('books', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###
