"""book table in stock bool updated

Revision ID: 5b3f58969114
Revises: ebfb427855a8
Create Date: 2026-07-08 12:13:23.897957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5b3f58969114'
down_revision: Union[str, Sequence[str], None] = 'ebfb427855a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'inStock',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'inStock',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
