"""relate users to book

Revision ID: e348166cb21d
Revises: 6c820ca941bb
Create Date: 2026-07-04 13:45:14.175977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e348166cb21d'
down_revision: Union[str, Sequence[str], None] = '6c820ca941bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('books', sa.Column('page_count', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'user_uid')
    op.drop_column('books', 'page_count')
    op.drop_column('books', 'language')
    # ### end Alembic commands ###
