"""tables updated

Revision ID: ebfb427855a8
Revises: a47130eab23a
Create Date: 2026-07-07 22:36:52.934544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ebfb427855a8'
down_revision: Union[str, Sequence[str], None] = 'a47130eab23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'inStock',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'inStock',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
